apiVersion: v1
data:
  goldholdings: "{{ .Values.holdings.gold }}"
  myholdingsstring: "{{ .Values.ourString }}"
  silverholdings: "{{ .Values.holdings.silver }}"
immutable: false
kind: ConfigMap
metadata:
  name: goldconfigmap
  labels:
{{- range $key, $value := .Values.labels }}
    {{ $key }}: "{{ $value }}"
{{- end }}
