apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldfrontend
  labels:
{{- range $key, $value := .Values.labels }}
    {{ $key }}: "{{ $value }}"
{{- end }}
    app: goldfrontend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: goldfrontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: goldfrontend
    spec:
      containers:
      - env:
        - name: goldholdings
          valueFrom:
            configMapKeyRef:
              key: goldholdings
              name: goldconfigmap
        - name: silverholdings
          valueFrom:
            configMapKeyRef:
              key: silverholdings
              name: goldconfigmap
        - name: myholdingsstring
          valueFrom:
            configMapKeyRef:
              key: myholdingsstring
              name: goldconfigmap
        image: {{ .Values.image }}:{{ .Values.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: container
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
